### ISSUE TITLE
Mount Errors on lancelot

### ISSUE THREAD

**Issue by manjotsidhu** [PitchBlackRecoveryProject/android_device_xiaomi_lancelot-pbrp#1]
![image](https://user-images.githubusercontent.com/22657113/95710104-a72b2500-0c7d-11eb-9650-4e45112100b2.png)
[logcat__2020-10-11-23-33-01.log](https://github.com/PitchBlackRecoveryProject/android_device_xiaomi_lancelot-pbrp/files/5363174/logcat__2020-10-11-23-33-01.log)
[recovery__2020-10-11-23-33-01.log](https://github.com/PitchBlackRecoveryProject/android_device_xiaomi_lancelot-pbrp/files/5363175/recovery__2020-10-11-23-33-01.log)
[dmesg__2020-10-11-23-33-01.log](https://github.com/PitchBlackRecoveryProject/android_device_xiaomi_lancelot-pbrp/files/5363176/dmesg__2020-10-11-23-33-01.log)

**Comment by AndroiableDroid** [comment]
https://github.com/PitchBlackRecoveryProject/android_bootable_recovery/commit/71f338ac50740a24ad7f26ad24ccf6606cf9bda9

**Comment by AndroiableDroid** [comment]
ask for rom whether it is based on a11 or a10?

**Comment by manjotsidhu** [comment]
He is running a10 GSI 
![image](https://user-images.githubusercontent.com/22657113/95713715-a5b12b00-0c84-11eb-8119-01658c750b83.png)
